- Cria o bando de dados
CREATE TABLESPACE tblTST LOCATION '/app';

CREATE DATABASE DB_TST TABLESPACE tblTST;

- Cria o Usuario

CREATE USER USERTST WITH PASSWORD '4<G1aUgc94M';

GRANT CONNECT ON DATABASE DB_TST TO USERTST;