
GRANT SELECT, INSERT, UPDATE, DELETE ON cliente TO USERTST;

GRANT SELECT, INSERT, UPDATE, DELETE ON filial TO USERTST;

GRANT SELECT, INSERT, UPDATE, DELETE ON produto TO USERTST;

GRANT SELECT, INSERT, UPDATE, DELETE ON venda TO USERTST;

GRANT SELECT, INSERT, UPDATE, DELETE ON venda_item TO USERTST;

